### ISSUE TITLE
Issue in QA task, baseline.py

### ISSUE THREAD

**Issue by wei118** [geek-ai/irgan#1]
Hi,
    After I and my superviser checked cafefully with your baseline.py, There are lots of issues happening. The description are the following:
  1. in line 184, actually you did not provide the model mentioned.
  2. in line 186, you did not claim Discriminator.Discriminator_pair_wise
  3. so if I change the Discriminator.Discriminator_pair_wise into Discriminator only, error will appear in line 197 stating that "pair" is not recognized.

Could you help solve the above problems or provide a precise description?

I am looking forward to your response and thank you for your time,
Ryan

**Comment by wabyking** [comment]
I may upload the wrong version of baseline.py  
1. in line 184, the pre-trained model is in the folder named "model", you should rename the  DIS_MODEL_FILE as "model/pre-trained.model".
2. in line 186, "Discriminator.Discriminator_pair_wise" should be "Discriminator.Discriminator_pair_wise "
3. Sorry, I cannot repeat your error, would you please provide more detail?

I have fixed these problem in this repository, I am sorry for my error. If there are any other problems, please do not hesitate to contact me.
Thanks for your issue.

**Comment by wei118** [comment]
Hello wabyking,
    Thank you for your quick response.
    After I replaced your updated baseline.py, the execution moved forward a little bit, and I got the following error showing in the picture attached. As a novice of Tensorflow, I am not sure where this type of error comes from. One guess is that the python version does matter in your case because I was using the 2.7 version. 
Best,
Ryan

![error1](https://user-images.githubusercontent.com/9281216/27266492-596e2844-54d4-11e7-897a-5012e450ca77.JPG)

**Comment by wabyking** [comment]
Thank Ryan,
I test the code in TensorFlow 0.12, it works. Sorry for that it does not support the newest version.
It may cost a little time to transfer it to the newest Tensorflow. I may update it if not busy. But I cannot confirm the time schedule.  
Benyou
