### ISSUE TITLE
请问下Pre-train相关的代码在哪？多谢多谢多谢！

### ISSUE THREAD

**Issue by guotong1988** [geek-ai/irgan#11]
也就是生成https://github.com/geek-ai/irgan/tree/master/Question-Answer/model
里的文件的代码在哪？
也就是`pre-trained.model`文件如何生成？
多谢多谢多谢！
@LantaoYu @wabyking @wnzhang

**Comment by wabyking** [comment]
直接用baseline.py中的方法训练的
