### ISSUE TITLE
ltr-gan-pointwise里的ndcg_at_k 

### ISSUE THREAD

**Issue by fword** [geek-ai/irgan#13]
这个ndcg算的有问题把，没有考虑2，1这种关系啊

**Comment by gy910210** [comment]
I implemented NDCG@k based on Wiki (https://en.wikipedia.org/wiki/Discounted_cumulative_gain#Normalized_DCG).
Also, We only have labels (0 or 1), not ranks (1 or 2).

**Comment by fword** [comment]
cat test.txt |awk '{print $1}'|sort|uniq
0
1
-1
2
why u says "We only have labels (0 or 1),"

**Comment by xf4fresh** [comment]
@fword 
你的答案在这里 
[`ndcg_5 = ndcg_at_k(sess, generator, query_pos_test, query_pos_train, query_url_feature, k=5)`](https://github.com/geek-ai/irgan/blob/master/ltr-gan/ltr-gan-pointwise/ltr_gan_d_nn_g_nn.py#L149)
[`query_pos_test = ut.get_query_pos(workdir + '/test.txt')`](https://github.com/geek-ai/irgan/blob/master/ltr-gan/ltr-gan-pointwise/ltr_gan_d_nn_g_nn.py#L31)
[`def get_query_pos(file)`](https://github.com/geek-ai/irgan/blob/master/ltr-gan/ltr-gan-pointwise/utils.py#L36)

留个微信,交流下问题?
