### ISSUE TITLE
Generative's loss function of Item Recommendation Method

### ISSUE THREAD

**Issue by LiuJiXiong** [geek-ai/irgan#17]
Would you mind telling me the Generative's loss function of Item Recommendation Method?thanks

**Comment by LantaoYu** [comment]
The equations can be found in the [paper](https://arxiv.org/pdf/1705.10513.pdf) and the implementation (gan loss) can be found [here](https://github.com/geek-ai/irgan/blob/master/item_recommendation/gen_model.py#L45).
