### ISSUE TITLE
ltr-gan/ltr-gan-pointwise/dis_model_pointwise_nn.py problem

### ISSUE THREAD

**Issue by zbmati** [geek-ai/irgan#4]
When running ltr_gan_d_nn_g_nn.py, a problem occured:
"/irgan-master/ltr-gan/ltr-gan-pointwise/dis_model_pointwise_nn.py", line 40, in __init__
    self.loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(self.pred_score, self.pred_data_label)
ValueError: Only call `sigmoid_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)
I guess this is caused by changes in new version of Tensorflow. Can you confirm that?

**Comment by pangolulu** [comment]
Yes, you can try ``labels=self.pred_data_label, logits=self.pred_score``.
