### ISSUE TITLE
How to train on Netflix?

### ISSUE THREAD

**Issue by akturtle** [geek-ai/irgan#6]
Hi, I've tried run you code about movielens-100k. But it is a really small dataset. When i try to train on Netflix with the same setting, it gives really bad performance and take a long time. Can you provide the training script of  netflix?

**Comment by wnzhang** [comment]
The Netflix dataset is relatively large and of course it requires much longer training time than movielens. According to the GANs theory, to guarantee the convergence, we normally need to train the discriminator more sufficiently. A more detailed discussion can be found [here](https://github.com/LantaoYu/SeqGAN/issues/18). So there is a trade off between the stability and training time. For demonstration in the movielens dataset, we can train the discriminator as fully as possible to get a stably improving performance, however in the netflix, considering the computation resource limitation, we need to retune the parameters in a predefined time window. This depends on how powerful your machine is.
